package bing.ui;

import bing.AppUI;
import bing.Constants;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import org.apache.commons.lang3.StringUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * 主题弹出框
 *
 * @author IceWee
 */
public class ThemeUI extends JFrame {

    private static final Logger LOGGER = LoggerFactory.getLogger(ThemeUI.class);
    private final AppUI app;
    private static final ImageIcon THEME_ICON = new ImageIcon(ThemeUI.class.getResource(Constants.ICON_THEME_PATH));
    private static final ImageIcon ICON_SALAF = new ImageIcon(ThemeUI.class.getResource(Constants.THEME_PREVIEW_SALAF));
    private static final ImageIcon ICON_SBLAF = new ImageIcon(ThemeUI.class.getResource(Constants.THEME_PREVIEW_SBLAF));
    private static final ImageIcon ICON_SCLAF = new ImageIcon(ThemeUI.class.getResource(Constants.THEME_PREVIEW_SCLAF));
    private static final ImageIcon ICON_SFOWLAF = new ImageIcon(ThemeUI.class.getResource(Constants.THEME_PREVIEW_SFOWLAF));
    private static final ImageIcon ICON_SGMLAF = new ImageIcon(ThemeUI.class.getResource(Constants.THEME_PREVIEW_SGMLAF));
    private static final ImageIcon ICON_SOBLAF = new ImageIcon(ThemeUI.class.getResource(Constants.THEME_PREVIEW_SOBLAF));
    private static final ImageIcon ICON_SOSLAF = new ImageIcon(ThemeUI.class.getResource(Constants.THEME_PREVIEW_SOSLAF));
    private static final ImageIcon ICON_SRGLAF = new ImageIcon(ThemeUI.class.getResource(Constants.THEME_PREVIEW_SRGLAF));
    private static final ImageIcon ICON_SMLAF = new ImageIcon(ThemeUI.class.getResource(Constants.THEME_PREVIEW_SMLAF));

    public ThemeUI(AppUI app) {
        initComponents();
        initThemeBlocks();
        this.app = app;
    }

    /**
     * 初始化主题颜色方块
     */
    private void initThemeBlocks() {
        this.setIconImage(THEME_ICON.getImage());
        this.substanceAutumnLookAndFeel.setIcon(ICON_SALAF);
        this.substanceBusinessLookAndFeel.setIcon(ICON_SBLAF);
        this.substanceCremeLookAndFeel.setIcon(ICON_SCLAF);
        this.substanceFieldOfWheatLookAndFeel.setIcon(ICON_SFOWLAF);
        this.substanceGreenMagicLookAndFeel.setIcon(ICON_SGMLAF);
        this.substanceOfficeBlue2007LookAndFeel.setIcon(ICON_SOBLAF);
        this.substanceOfficeSilver2007LookAndFeel.setIcon(ICON_SOSLAF);
        this.substanceRavenGraphiteLookAndFeel.setIcon(ICON_SRGLAF);
        this.substanceMagmaLookAndFeel.setIcon(ICON_SMLAF);
    }

    /**
     * 通过主题预览图片路径解析主题名称
     *
     * @param iconPath
     * @return
     */
    private String parseThemeNameByIconPath(String iconPath) {
        String themeName = Constants.THEME_DEFAULT;
        if (StringUtils.isNotBlank(iconPath)) {
            themeName = StringUtils.substringAfterLast(iconPath, "/");
            themeName = StringUtils.substringBeforeLast(themeName, ".");
        }
        return themeName;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        substanceCremeLookAndFeel = new javax.swing.JLabel();
        substanceAutumnLookAndFeel = new javax.swing.JLabel();
        substanceBusinessLookAndFeel = new javax.swing.JLabel();
        substanceFieldOfWheatLookAndFeel = new javax.swing.JLabel();
        substanceGreenMagicLookAndFeel = new javax.swing.JLabel();
        substanceOfficeBlue2007LookAndFeel = new javax.swing.JLabel();
        substanceOfficeSilver2007LookAndFeel = new javax.swing.JLabel();
        substanceRavenGraphiteLookAndFeel = new javax.swing.JLabel();
        substanceMagmaLookAndFeel = new javax.swing.JLabel();

        setTitle("更换主题");
        setAlwaysOnTop(true);
        setResizable(false);

        substanceCremeLookAndFeel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        substanceCremeLookAndFeel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        substanceCremeLookAndFeel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        substanceCremeLookAndFeel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                substanceCremeLookAndFeelMouseClicked(evt);
            }
        });

        substanceAutumnLookAndFeel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        substanceAutumnLookAndFeel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        substanceAutumnLookAndFeel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        substanceAutumnLookAndFeel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                substanceAutumnLookAndFeelMouseClicked(evt);
            }
        });

        substanceBusinessLookAndFeel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        substanceBusinessLookAndFeel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        substanceBusinessLookAndFeel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        substanceBusinessLookAndFeel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                substanceBusinessLookAndFeelMouseClicked(evt);
            }
        });

        substanceFieldOfWheatLookAndFeel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        substanceFieldOfWheatLookAndFeel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        substanceFieldOfWheatLookAndFeel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        substanceFieldOfWheatLookAndFeel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                substanceFieldOfWheatLookAndFeelMouseClicked(evt);
            }
        });

        substanceGreenMagicLookAndFeel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        substanceGreenMagicLookAndFeel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        substanceGreenMagicLookAndFeel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        substanceGreenMagicLookAndFeel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                substanceGreenMagicLookAndFeelMouseClicked(evt);
            }
        });

        substanceOfficeBlue2007LookAndFeel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        substanceOfficeBlue2007LookAndFeel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        substanceOfficeBlue2007LookAndFeel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        substanceOfficeBlue2007LookAndFeel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                substanceOfficeBlue2007LookAndFeelMouseClicked(evt);
            }
        });

        substanceOfficeSilver2007LookAndFeel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        substanceOfficeSilver2007LookAndFeel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        substanceOfficeSilver2007LookAndFeel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        substanceOfficeSilver2007LookAndFeel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                substanceOfficeSilver2007LookAndFeelMouseClicked(evt);
            }
        });

        substanceRavenGraphiteLookAndFeel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        substanceRavenGraphiteLookAndFeel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        substanceRavenGraphiteLookAndFeel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        substanceRavenGraphiteLookAndFeel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                substanceRavenGraphiteLookAndFeelMouseClicked(evt);
            }
        });

        substanceMagmaLookAndFeel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        substanceMagmaLookAndFeel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        substanceMagmaLookAndFeel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        substanceMagmaLookAndFeel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                substanceMagmaLookAndFeelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(substanceFieldOfWheatLookAndFeel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(substanceGreenMagicLookAndFeel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(substanceOfficeBlue2007LookAndFeel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(substanceAutumnLookAndFeel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(substanceBusinessLookAndFeel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(substanceCremeLookAndFeel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(substanceOfficeSilver2007LookAndFeel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(substanceRavenGraphiteLookAndFeel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(substanceMagmaLookAndFeel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(substanceCremeLookAndFeel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(substanceAutumnLookAndFeel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(substanceBusinessLookAndFeel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(substanceOfficeBlue2007LookAndFeel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(substanceFieldOfWheatLookAndFeel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(substanceGreenMagicLookAndFeel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(substanceMagmaLookAndFeel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(substanceOfficeSilver2007LookAndFeel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(substanceRavenGraphiteLookAndFeel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void substanceAutumnLookAndFeelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_substanceAutumnLookAndFeelMouseClicked
        changeTheme(evt);
    }//GEN-LAST:event_substanceAutumnLookAndFeelMouseClicked

    private void substanceBusinessLookAndFeelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_substanceBusinessLookAndFeelMouseClicked
        changeTheme(evt);
    }//GEN-LAST:event_substanceBusinessLookAndFeelMouseClicked

    private void substanceCremeLookAndFeelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_substanceCremeLookAndFeelMouseClicked
        changeTheme(evt);
    }//GEN-LAST:event_substanceCremeLookAndFeelMouseClicked

    private void substanceFieldOfWheatLookAndFeelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_substanceFieldOfWheatLookAndFeelMouseClicked
        changeTheme(evt);
    }//GEN-LAST:event_substanceFieldOfWheatLookAndFeelMouseClicked

    private void substanceGreenMagicLookAndFeelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_substanceGreenMagicLookAndFeelMouseClicked
        changeTheme(evt);
    }//GEN-LAST:event_substanceGreenMagicLookAndFeelMouseClicked

    private void substanceOfficeBlue2007LookAndFeelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_substanceOfficeBlue2007LookAndFeelMouseClicked
        changeTheme(evt);
    }//GEN-LAST:event_substanceOfficeBlue2007LookAndFeelMouseClicked

    private void substanceOfficeSilver2007LookAndFeelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_substanceOfficeSilver2007LookAndFeelMouseClicked
        changeTheme(evt);
    }//GEN-LAST:event_substanceOfficeSilver2007LookAndFeelMouseClicked

    private void substanceRavenGraphiteLookAndFeelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_substanceRavenGraphiteLookAndFeelMouseClicked
        changeTheme(evt);
    }//GEN-LAST:event_substanceRavenGraphiteLookAndFeelMouseClicked

    private void substanceMagmaLookAndFeelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_substanceMagmaLookAndFeelMouseClicked
        changeTheme(evt);
    }//GEN-LAST:event_substanceMagmaLookAndFeelMouseClicked

    /**
     * 点击不同主题块改变主题
     *
     * @param evt
     */
    private void changeTheme(MouseEvent evt) {
        JLabel label = (JLabel) evt.getSource();
        String iconPath = label.getIcon().toString();
        String themeShortName = parseThemeNameByIconPath(iconPath);
        app.setCustomTheme(themeShortName);
        LOGGER.debug("设置主题{}...", themeShortName);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel substanceAutumnLookAndFeel;
    private javax.swing.JLabel substanceBusinessLookAndFeel;
    private javax.swing.JLabel substanceCremeLookAndFeel;
    private javax.swing.JLabel substanceFieldOfWheatLookAndFeel;
    private javax.swing.JLabel substanceGreenMagicLookAndFeel;
    private javax.swing.JLabel substanceMagmaLookAndFeel;
    private javax.swing.JLabel substanceOfficeBlue2007LookAndFeel;
    private javax.swing.JLabel substanceOfficeSilver2007LookAndFeel;
    private javax.swing.JLabel substanceRavenGraphiteLookAndFeel;
    // End of variables declaration//GEN-END:variables
}
